[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "python310"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build:webpack",
  "npm run build:grunt"
]

[start]
cmd = "npm start"

[healthcheck]
path = "/health"
interval = 10
timeout = 5
