[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "python310"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build:webpack",
  "npm run build:grunt"
]

[start]
cmd = "npm start"

[healthcheck]
path = "/health"
interval = 5  # Vérifie toutes les 5 secondes
timeout = 10   # Délai d'attente de 10 secondes
start_period = 30  # Donne 30 secondes à l'app pour démarrer
